CREATE TABLE automation_email (
	id VARCHAR(255) NOT NULL PRIMARY KEY,
	automation_id VARCHAR(255) NOT NULL REFERENCES automation (id),
	authenticate BOOL,
	auto_footer BOOL,
	auto_tweet BOOL,
	clicktale VARCHAR(255),
	content_type VARCHAR(255),
	create_time VARCHAR(255),
	delay_action VARCHAR(255),
	delay_action_description VARCHAR(255),
	delay_amount INT,
	delay_direction VARCHAR(255),
	delay_full_description VARCHAR(255),
	delay_type VARCHAR(255),
	drag_and_drop BOOL,
	fb_comments BOOL,
	from_name VARCHAR(255),
	google_analytics VARCHAR(255),
	inline_css BOOL,
	"position" INT,
	reply_to VARCHAR(255),
	send_time VARCHAR(255),
	start_time VARCHAR(255),
	status VARCHAR(255),
	subject_line VARCHAR(255),
	template_id INT,
	title VARCHAR(255),
	track_ecomm_360 BOOL,
	track_goals BOOL,
	track_html_clicks BOOL,
	track_opens BOOL,
	track_text_clicks BOOL
);