CREATE TABLE list (
	id VARCHAR(255) NOT NULL PRIMARY KEY,
	beamer_address VARCHAR(255),
	contact_address_1 VARCHAR(255),
	contact_address_2 VARCHAR(255),
	contact_city VARCHAR(255),
	contact_company VARCHAR(255),
	contact_country VARCHAR(255),
	contact_state VARCHAR(255),
	contact_zip VARCHAR(255),
	date_created VARCHAR(255),
	default_from_email VARCHAR(255),
	default_from_name VARCHAR(255),
	default_language VARCHAR(255),
	default_subject VARCHAR(255),
	email_type_option BOOL,
	list_rating INT,
	name VARCHAR(255),
	notify_on_subscribe VARCHAR(255),
	notify_on_unsubscribe VARCHAR(255),
	permission_reminder VARCHAR(255),
	subscribe_url_long VARCHAR(255),
	subscribe_url_short VARCHAR(255),
	use_archive_bar BOOL,
	visibility VARCHAR(255)
);